import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Image from 'next/image'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>Loja Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.container} >
          <h1>Página Inicial</h1>
          <h2>Sistema de Gerenciamento de Livros - Banco de dados - Mongodb</h2>

          <Image
            src="/images/nextj.png"
            width={500}
            height={500}
            alt="Picture of the author"
          />

          <div className="infoContent">
            <section className="box">
              <span>Aluno: Gustavo Igor da Silva</span><br/>
              <span>Mat:202305342613</span>
            </section>
            <section className="box">
            <span>Tutor(a): Andre Przewodowski Filho.</span>
            </section>
          </div>
        </div>
      </main>
    </div>
  )
}
